### ISSUE TITLE
Add a time signature changer

### ISSUE THREAD

**Issue by dcallus** [fillmaster/fillMaster#12]
Add ability to change time signature.

- [x] #2
- [x] Add Time Signature to patternMaker
- [x] Edit react-pro-metronome library to allow for different time signatures 
- [x] Add tests for basic time sigs
- [x] Create custom dropdown menus so defaults are clear
- [x] Add dropdown menus for note divisions, timeSig top and bottom
- [x] Make time sig persist when restarting metronome.
- [x] Calculate and select PlayNotes defaults when changing bottom (edit: or top) half of time sig
- [x] Hide invalid options (e.g. quarters in 5/8)
- [x] Have correct number of red blocks per beats per bar
- [x] Add centered parameter for buttons which defaults to true. turn off for playNotes
- [x] Add highlight default parameter. Default to off (and use for the time signature halves, too confusing but very useful for subdivision).
- [x] Fix logic so that defaults are enforced on the string level (i.e. 5/8 should not be faster than 5/4)
- [x] Force default PlayNotes on countIn
- [x] Basic layout change. Hide steps after complete. max width 580. centered (so buttons display better) - and have PlayNotes on right hand side of timeSig
- [x] #18
- [x] Calculate Advice e.g. (first note only, half-time, double-time)
- [x] Fix stop reset bug

**Comment by dcallus** [comment]
Complete. Merged.
