### ISSUE TITLE
Epic: Exact tempo & Tap Tempo

### ISSUE THREAD

**Issue by dcallus** [fillmaster/fillMaster#24]
- [ ] Tap tempo is going to need an audio preview. Other things in the app are going to need previews too without interfering with the patternMaker. The best approach would be to try and create a parent class for PatternMaker called PatternMakerBase. Probably most features will be moved up to the parent class (with exception of things like countins and fills). PatternMaker class will have the singleton logic. PatternMakerBase class will allow multiple instances. The preview could be done in the base class, but probably best to make a new child class called TempoPreviewMaker.
- [ ] Make TempoPreviewMaker default to 4/4 - all sound '2'. Must have no fillString etc.
- [ ] Move the labels (from section 1) showing the current tempo to elsewhere so that they do not overlap when the minimum distance is taken off.
- [ ] Remove minimum distance between lower and upper tempo
- [ ] Add a toggle switch to toggle between 'tempo range' and 'exact tempo'.
- [ ] When exact tempo is on it says 'choose a tempo' instead of 'choose a tempo range'. Also update section 5 so that it now says 'your chosen tempo' with a stationary number instead of a randomised tempo - or simply remove step 5. See which looks better.
- [ ] Add logic so that when in 'tempo range' mode and the two tempos are on top of each other it will switch to 'exact tempo', i.e. one disappears and the toggle changes.
- [ ] Add a tap tempo button on 'exact tempo mode'. Perhaps get inspiration from here: https://github.com/classicwfl/React-Metronome-With-Tap-Tempo/blob/master/src/Metronome.js - It should register after 3 taps. It should then play for 3-4 clicks. Probably allow updating of tempo as it's clicking. So you can keep clicking/tapping and the tempo will update and it will play 3-4 clicks after your final click (probably 4 including final click, whatever sounds best).
- [ ] Slider value should move accordingly
- [ ] Add visual feedback that the 3 clicks/taps have registered. A white flash of the screen or a lit up button etc.

Stretch goal 1. Try having two tap tempo buttons lowest tempo and highest tempo on tempo range mode. See if it looks okay or is too convoluted.
Stretch goal 2. Have an audio preview of the tempo on slider drag.
Stretch goal 3. Add Italian tempo names depending on the chosen tempo or tempo range. 
Stretch goal 4. Add currently chosen settings to local storage.

**Comment by dcallus** [comment]
The app is due a re-design from the ground-up, but it's probably best to get this feature up first as the redesign will take time.

So go with something like the following design for now which fits into the current design. 

![proposed_1](https://user-images.githubusercontent.com/80394290/178101622-1e0cd993-3d08-4bb8-b309-55fe4571832b.jpg)

**Comment by dcallus** [comment]
@ninad-d - edit: okay. I updated the epic branch to contain a new base class above pattern (see #56 ). There is now also a new class called TempoPreview. You won't need this straight away, but eventually you will.

I've rewritten this issue to clean it up a bit so that your section is separate from the UI and I'll do the UI stuff. Let me know if you have any questions.

For an example of a good tap tempo see the free app: The Metronome by SoundBrenner (iOS and Android) install and click 'Player' on the bottom.
